// Code generated by "stringer -type=EtherType"; DO NOT EDIT.

package dgrams

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EtherTypeIPv4-2048]
	_ = x[EtherTypeARP-2054]
	_ = x[EtherTypeWakeOnLAN-2114]
	_ = x[EtherTypeTRILL-8947]
	_ = x[EtherTypeDECnetPhase4-24579]
	_ = x[EtherTypeRARP-32821]
	_ = x[EtherTypeAppleTalk-32923]
	_ = x[EtherTypeAARP-33011]
	_ = x[EtherTypeIPX1-33079]
	_ = x[EtherTypeIPX2-33080]
	_ = x[EtherTypeQNXQnet-33284]
	_ = x[EtherTypeIPv6-34525]
	_ = x[EtherTypeEthernetFlowControl-34824]
	_ = x[EtherTypeIEEE802_3-34825]
	_ = x[EtherTypeCobraNet-34841]
	_ = x[EtherTypeMPLSUnicast-34887]
	_ = x[EtherTypeMPLSMulticast-34888]
	_ = x[EtherTypePPPoEDiscovery-34915]
	_ = x[EtherTypePPPoESession-34916]
	_ = x[EtherTypeJumboFrames-34928]
	_ = x[EtherTypeHomePlug1_0MME-34939]
	_ = x[EtherTypeIEEE802_1X-34958]
	_ = x[EtherTypePROFINET-34962]
	_ = x[EtherTypeHyperSCSI-34970]
	_ = x[EtherTypeAoE-34978]
	_ = x[EtherTypeEtherCAT-34980]
	_ = x[EtherTypeEthernetPowerlink-34987]
	_ = x[EtherTypeLLDP-35020]
	_ = x[EtherTypeSERCOS3-35021]
	_ = x[EtherTypeHomePlugAVMME-35041]
	_ = x[EtherTypeMRP-35043]
	_ = x[EtherTypeIEEE802_1AE-35045]
	_ = x[EtherTypeIEEE1588-35063]
	_ = x[EtherTypeIEEE802_1ag-35074]
	_ = x[EtherTypeFCoE-35078]
	_ = x[EtherTypeFCoEInit-35092]
	_ = x[EtherTypeRoCE-35093]
	_ = x[EtherTypeCTP-36864]
	_ = x[EtherTypeVeritasLLT-51966]
	_ = x[EtherTypeVLAN-33024]
	_ = x[EtherTypeServiceVLAN-34984]
}

const _EtherType_name = "EtherTypeIPv4EtherTypeARPEtherTypeWakeOnLANEtherTypeTRILLEtherTypeDECnetPhase4EtherTypeRARPEtherTypeAppleTalkEtherTypeAARPEtherTypeVLANEtherTypeIPX1EtherTypeIPX2EtherTypeQNXQnetEtherTypeIPv6EtherTypeEthernetFlowControlEtherTypeIEEE802_3EtherTypeCobraNetEtherTypeMPLSUnicastEtherTypeMPLSMulticastEtherTypePPPoEDiscoveryEtherTypePPPoESessionEtherTypeJumboFramesEtherTypeHomePlug1_0MMEEtherTypeIEEE802_1XEtherTypePROFINETEtherTypeHyperSCSIEtherTypeAoEEtherTypeEtherCATEtherTypeServiceVLANEtherTypeEthernetPowerlinkEtherTypeLLDPEtherTypeSERCOS3EtherTypeHomePlugAVMMEEtherTypeMRPEtherTypeIEEE802_1AEEtherTypeIEEE1588EtherTypeIEEE802_1agEtherTypeFCoEEtherTypeFCoEInitEtherTypeRoCEEtherTypeCTPEtherTypeVeritasLLT"

var _EtherType_map = map[EtherType]string{
	2048:  _EtherType_name[0:13],
	2054:  _EtherType_name[13:25],
	2114:  _EtherType_name[25:43],
	8947:  _EtherType_name[43:57],
	24579: _EtherType_name[57:78],
	32821: _EtherType_name[78:91],
	32923: _EtherType_name[91:109],
	33011: _EtherType_name[109:122],
	33024: _EtherType_name[122:135],
	33079: _EtherType_name[135:148],
	33080: _EtherType_name[148:161],
	33284: _EtherType_name[161:177],
	34525: _EtherType_name[177:190],
	34824: _EtherType_name[190:218],
	34825: _EtherType_name[218:236],
	34841: _EtherType_name[236:253],
	34887: _EtherType_name[253:273],
	34888: _EtherType_name[273:295],
	34915: _EtherType_name[295:318],
	34916: _EtherType_name[318:339],
	34928: _EtherType_name[339:359],
	34939: _EtherType_name[359:382],
	34958: _EtherType_name[382:401],
	34962: _EtherType_name[401:418],
	34970: _EtherType_name[418:436],
	34978: _EtherType_name[436:448],
	34980: _EtherType_name[448:465],
	34984: _EtherType_name[465:485],
	34987: _EtherType_name[485:511],
	35020: _EtherType_name[511:524],
	35021: _EtherType_name[524:540],
	35041: _EtherType_name[540:562],
	35043: _EtherType_name[562:574],
	35045: _EtherType_name[574:594],
	35063: _EtherType_name[594:611],
	35074: _EtherType_name[611:631],
	35078: _EtherType_name[631:644],
	35092: _EtherType_name[644:661],
	35093: _EtherType_name[661:674],
	36864: _EtherType_name[674:686],
	51966: _EtherType_name[686:705],
}

func (i EtherType) String() string {
	if str, ok := _EtherType_map[i]; ok {
		return str
	}
	return "EtherType(" + strconv.FormatInt(int64(i), 10) + ")"
}
