// Code generated by "stringer -type=State"; DO NOT EDIT.

package tcpctl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateClosed-0]
	_ = x[StateListen-1]
	_ = x[StateSynRcvd-2]
	_ = x[StateSynSent-3]
	_ = x[StateEstablished-4]
	_ = x[StateFinWait1-5]
	_ = x[StateFinWait2-6]
	_ = x[StateClosing-7]
	_ = x[StateTimeWait-8]
	_ = x[StateCloseWait-9]
	_ = x[StateLastAck-10]
}

const _State_name = "StateClosedStateListenStateSynRcvdStateSynSentStateEstablishedStateFinWait1StateFinWait2StateClosingStateTimeWaitStateCloseWaitStateLastAck"

var _State_index = [...]uint8{0, 11, 22, 34, 46, 62, 75, 88, 100, 113, 127, 139}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
